return {
  {
    "catppuccin/nvim",
    opts = {
      --  term_colors = true,
      transparent_background = false,
      background = {
        light = "mocha",
        dark = "mocha",
      },
      color_overrides = {
        mocha = {
          rosewater = "#875f5f",
          flamingo = "#875f5f",
          pink = "#87875f",
          mauve = "#87875f",
          red = "#875f5f",
          maroon = "#875f5f",
          peach = "#dfdfaf",
          yellow = "#dfdfaf",
          green = "#87875f",
          teal = "#5e81ac",
          sky = "#5e81ac",
          sapphire = "#5e81ac",
          blue = "#5f5f87",
          lavender = "#5f5f87",
          text = "#cdcbe6",
          subtext1 = "#BDAE8B",
          subtext0 = "#A69372",
          overlay2 = "#8C7A58",
          overlay1 = "#735F3F",
          overlay0 = "#5A4525",
          surface2 = "#4B4F51",
          surface1 = "#2f2f2f",
          surface0 = "#7b838c",
          base = "#2f2f2f",
          mantle = "#4d5159",
          crust = "#636a73",
        },
      },
      styles = {
        comments = {},
        conditionals = {},
        loops = {},
        functions = {},
        keywords = {},
        strings = {},
        variables = {},
        numbers = {},
        booleans = {},
        properties = {},
        types = {},
      },
    },
  },
}
